#!/usr/bin/env node
/**
 * Create a PR for completed Ralph Wiggum tasks
 * Used by Ralph Wiggum workflow to create milestone PRs
 */

import { readFileSync, existsSync, writeFileSync } from 'fs';
import { execSync } from 'child_process';
import yaml from 'js-yaml';

const TASKS_FILE = '.ralph/tasks.yaml';
const PROGRESS_FILE = '.ralph/progress.md';

function loadTasks() {
  if (!existsSync(TASKS_FILE)) {
    console.error('❌ Tasks file not found:', TASKS_FILE);
    process.exit(1);
  }

  try {
    const content = readFileSync(TASKS_FILE, 'utf8');
    return yaml.load(content);
  } catch (error) {
    console.error('❌ Failed to parse tasks file:', error.message);
    process.exit(1);
  }
}

function getCurrentBranch() {
  try {
    return execSync('git rev-parse --abbrev-ref HEAD', { encoding: 'utf8' }).trim();
  } catch (error) {
    console.error('❌ Failed to get current branch:', error.message);
    process.exit(1);
  }
}

function getTasksSinceLastPR(tasks) {
  const lastPRTask = tasks.last_pr_task_id || null;
  const allTasks = tasks.tasks || [];
  
  if (!lastPRTask) {
    // Return all completed tasks
    return allTasks.filter(t => t.status === 'completed');
  }

  // Find last PR task index
  const lastPRIndex = allTasks.findIndex(t => t.id === lastPRTask);
  if (lastPRIndex === -1) {
    return allTasks.filter(t => t.status === 'completed');
  }

  // Return completed tasks after last PR
  return allTasks
    .slice(lastPRIndex + 1)
    .filter(t => t.status === 'completed');
}

function getPhaseFromTaskId(taskId) {
  if (taskId?.startsWith('P0-')) return 'P0';
  if (taskId?.startsWith('P1-')) return 'P1';
  if (taskId?.startsWith('P2-')) return 'P2';
  if (taskId?.startsWith('P3-')) return 'P3';
  return 'Unknown';
}

function generatePRTitle(tasks) {
  const tasksSincePR = getTasksSinceLastPR(tasks);
  if (tasksSincePR.length === 0) {
    return 'Ralph Wiggum: Milestone PR';
  }

  const firstTask = tasksSincePR[0];
  const lastTask = tasksSincePR[tasksSincePR.length - 1];
  const phase = getPhaseFromTaskId(firstTask.id);

  return `feat(ralph): ${phase} tasks ${firstTask.id} - ${lastTask.id}`;
}

function generatePRBody(tasks) {
  const tasksSincePR = getTasksSinceLastPR(tasks);
  const phase = tasksSincePR.length > 0 ? getPhaseFromTaskId(tasksSincePR[0].id) : 'Unknown';

  let body = `## Ralph Wiggum Milestone PR\n\n`;
  body += `This PR contains ${tasksSincePR.length} completed tasks from the Ralph Wiggum autonomous coding loop.\n\n`;
  body += `### Phase: ${phase}\n\n`;
  body += `### Completed Tasks\n\n`;

  for (const task of tasksSincePR) {
    body += `- **${task.id}**: ${task.name}\n`;
    if (task.description) {
      body += `  - ${task.description}\n`;
    }
  }

  body += `\n### Test Coverage\n\n`;
  body += `- All tasks include appropriate tests (unit/integration/component)\n`;
  body += `- Coverage thresholds verified (80%+ for new code)\n`;
  body += `- See progress.md for detailed coverage information\n\n`;

  body += `### Quality Gates\n\n`;
  body += `- ✅ TypeScript compilation passes\n`;
  body += `- ✅ Linting passes\n`;
  body += `- ✅ Unit tests pass\n`;
  body += `- ✅ Test coverage meets thresholds\n`;
  body += `- ✅ Production build succeeds\n\n`;

  body += `### Next Steps\n\n`;
  body += `- Review changes\n`;
  body += `- Run E2E tests if applicable\n`;
  body += `- Merge when ready\n\n`;

  body += `---\n\n`;
  body += `*Generated by Ralph Wiggum autonomous coding loop*\n`;

  return body;
}

function createPRBranch(tasks) {
  const tasksSincePR = getTasksSinceLastPR(tasks);
  if (tasksSincePR.length === 0) {
    console.error('❌ No completed tasks since last PR');
    process.exit(1);
  }

  const firstTask = tasksSincePR[0];
  const lastTask = tasksSincePR[tasksSincePR.length - 1];
  const phase = getPhaseFromTaskId(firstTask.id);
  const branchName = `ralph/${phase.toLowerCase()}-${firstTask.id.toLowerCase()}-${lastTask.id.toLowerCase()}`;

  try {
    // Check if branch already exists
    try {
      execSync(`git show-ref --verify --quiet refs/heads/${branchName}`, { stdio: 'ignore' });
      console.log(`⚠️  Branch ${branchName} already exists. Using existing branch.`);
    } catch {
      // Branch doesn't exist, create it
      execSync(`git checkout -b ${branchName}`, { stdio: 'inherit' });
      console.log(`✅ Created branch: ${branchName}`);
    }

    return branchName;
  } catch (error) {
    console.error('❌ Failed to create branch:', error.message);
    process.exit(1);
  }
}

function updateTasksFile(tasks, branchName, prNumber) {
  const tasksSincePR = getTasksSinceLastPR(tasks);
  const lastTask = tasksSincePR.length > 0 ? tasksSincePR[tasksSincePR.length - 1] : null;
  const phase = lastTask ? getPhaseFromTaskId(lastTask.id) : null;

  tasks.last_pr_branch = branchName;
  tasks.last_pr_task_id = lastTask?.id || null;
  tasks.last_pr_phase = phase;
  tasks.last_pr_number = prNumber;
  tasks.last_pr_date = new Date().toISOString();

  try {
    const yamlContent = yaml.dump(tasks, { 
      lineWidth: -1,
      noRefs: true,
      sortKeys: false,
    });
    writeFileSync(TASKS_FILE, yamlContent, 'utf8');
    console.log(`✅ Updated ${TASKS_FILE} with PR info`);
  } catch (error) {
    console.error('❌ Failed to update tasks file:', error.message);
    process.exit(1);
  }
}

function createPRWithGHCLI(branchName, title, body) {
  try {
    // Check if gh CLI is available
    execSync('gh --version', { stdio: 'ignore' });
  } catch {
    console.log('⚠️  GitHub CLI (gh) not available. PR must be created manually.');
    console.log('\n📋 PR Details:');
    console.log(`   Branch: ${branchName}`);
    console.log(`   Title: ${title}`);
    console.log(`\n   Body:\n${body}\n`);
    return null;
  }

  try {
    // Push branch first
    console.log('📤 Pushing branch to remote...');
    execSync(`git push -u origin ${branchName}`, { stdio: 'inherit' });

    // Create PR
    console.log('🔨 Creating PR with GitHub CLI...');
    const output = execSync(
      `gh pr create --title "${title}" --body "${body.replace(/"/g, '\\"')}" --base main`,
      { encoding: 'utf8' }
    );

    // Extract PR number from output
    const match = output.match(/pull\/(\d+)/);
    const prNumber = match ? match[1] : null;

    console.log(`✅ PR created: ${output.trim()}`);
    return prNumber;
  } catch (error) {
    console.error('❌ Failed to create PR:', error.message);
    console.log('\n📋 Create PR manually:');
    console.log(`   Branch: ${branchName}`);
    console.log(`   Title: ${title}`);
    console.log(`\n   Body:\n${body}\n`);
    return null;
  }
}

function main() {
  console.log('🚀 Creating PR for Ralph Wiggum milestone...\n');

  const tasks = loadTasks();
  const currentBranch = getCurrentBranch();

  // Create PR branch
  const branchName = createPRBranch(tasks);

  // Generate PR content
  const title = generatePRTitle(tasks);
  const body = generatePRBody(tasks);

  // Create PR
  const prNumber = createPRWithGHCLI(branchName, title, body);

  // Update tasks file
  updateTasksFile(tasks, branchName, prNumber || 'manual');

  console.log('\n✅ PR workflow complete!');
  console.log(`   Continue working on branch: ${branchName}\n`);
}

main();
